"""Insight Report Generator — creates rich 'Brain Briefing' pages in Notion via MCP."""

from __future__ import annotations

import datetime

from rich.console import Console

from notion_reverse_autopilot.analyzer import AnalysisResult
from notion_reverse_autopilot.notion_mcp import NotionMCPClient
from notion_reverse_autopilot.scanner import WorkspaceSnapshot

console = Console()


class InsightReportGenerator:
    def __init__(self, client: NotionMCPClient):
        self.client = client

    async def generate_briefing(self, snapshot: WorkspaceSnapshot, analysis: AnalysisResult) -> str | None:
        now = datetime.datetime.now(datetime.timezone.utc)
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M UTC")

        children: list[dict] = []

        # Header
        children.append(_heading(f"Brain Briefing — {date_str}", 1))
        children.append(_paragraph(f"Generated at {time_str} by Notion Reverse Autopilot"))
        children.append(_divider())

        # Workspace Health Score
        children.append(_heading("Workspace Health", 2))
        score = analysis.health_score
        bar = _score_bar(score)
        children.append(_callout(f"Health Score: {score:.0f}/100\n{bar}"))
        children.append(_paragraph(
            f"Total items: {snapshot.total_items} | "
            f"Chaos score: {snapshot.chaos.total_chaos_score:.1f} | "
            f"Untagged: {snapshot.chaos.untagged_pages} | "
            f"Orphans: {snapshot.chaos.orphan_pages} | "
            f"Empty: {snapshot.chaos.empty_pages}"
        ))
        children.append(_divider())

        # Workspace Summary
        if analysis.workspace_summary:
            children.append(_heading("Your Workspace Profile", 2))
            children.append(_callout(analysis.workspace_summary))
            children.append(_divider())

        # Cognitive Insights
        insight_groups = {
            "pattern": ("Recurring Patterns", "🔄"),
            "strength": ("Your Strengths", "💪"),
            "contradiction": ("Contradictions Found", "⚡"),
            "blind_spot": ("Blind Spots", "👁️"),
            "prediction": ("Predictions", "🔮"),
        }

        for itype, (heading, emoji) in insight_groups.items():
            matching = [i for i in analysis.insights if i.insight_type == itype]
            if not matching:
                continue
            children.append(_heading(f"{emoji} {heading}", 2))
            for insight in matching:
                conf_pct = f"{insight.confidence * 100:.0f}%"
                children.append(_callout(
                    f"{insight.title} (confidence: {conf_pct})\n\n{insight.description}",
                ))
                if insight.evidence:
                    children.append(_paragraph(f"Evidence: {', '.join(insight.evidence[:5])}"))

        children.append(_divider())

        # Hidden Connections
        if analysis.connections:
            children.append(_heading("Hidden Connections Discovered", 2))
            for conn in analysis.connections[:10]:
                rel_labels = {"related_to": "Related", "contradicts": "Contradicts", "builds_on": "Builds on", "duplicate_of": "Duplicate"}
                label = rel_labels.get(conn.relationship, "Connected")
                children.append(_bullet(
                    f"[{label}] \"{conn.page_a_title}\" <-> \"{conn.page_b_title}\" — {conn.explanation}"
                ))
            children.append(_divider())

        # Topic Clusters
        if analysis.topic_clusters:
            children.append(_heading("Topic Clusters", 2))
            for cluster, page_ids in list(analysis.topic_clusters.items())[:10]:
                children.append(_bullet(f"{cluster.title()}: {len(page_ids)} pages"))

        # Footer
        children.append(_divider())
        children.append(_callout(
            "This briefing was auto-generated by Notion Reverse Autopilot. "
            "Check the Autopilot Changelog for all changes made to your workspace.",
        ))

        try:
            page = await self.client.create_page(
                properties={
                    "title": {"title": [{"text": {"content": f"Brain Briefing — {date_str}"}}]}
                },
                children=children[:100],
            )
            page_url = page.get("url", page.get("id", ""))
            console.print(f"[bold green]Brain Briefing created:[/] {page_url}")
            return page.get("id")
        except Exception as e:
            console.print(f"[bold red]Failed to create briefing: {e}[/]")
            return None


# ── Block builders ───────────────────────────────────────────────

def _heading(text: str, level: int = 1) -> dict:
    key = f"heading_{level}"
    return {"object": "block", "type": key, key: {"rich_text": [{"type": "text", "text": {"content": text}}]}}


def _paragraph(text: str) -> dict:
    return {"object": "block", "type": "paragraph", "paragraph": {"rich_text": [{"type": "text", "text": {"content": text}}]}}


def _bullet(text: str) -> dict:
    return {"object": "block", "type": "bulleted_list_item", "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": text}}]}}


def _divider() -> dict:
    return {"object": "block", "type": "divider", "divider": {}}


def _callout(text: str) -> dict:
    return {
        "object": "block",
        "type": "callout",
        "callout": {
            "rich_text": [{"type": "text", "text": {"content": text}}],
            "icon": {"type": "emoji", "emoji": "💡"},
        },
    }


def _score_bar(score: float) -> str:
    filled = int(score / 5)
    empty = 20 - filled
    return "█" * filled + "░" * empty
